networks:
  ps-net:
    driver: bridge

volumes:
  grafana_data: { }
  mariadb_data:

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: on-failure
    networks:
      - ps-net

  mariadb:
    image: mariadb:latest
    container_name: ${DB_HOST}
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./:/docker-entrypoint-initdb.d
    networks:
      - ps-net

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    ports:
      - "7777:8080"
    expose:
      - 8080
    volumes:
      - ./adminer.css:/var/www/html/adminer.css
    networks:
      - ps-net

  web:
    build:
      context: .
    container_name: web
    ports:
      - "5004:5000"
    expose:
      - 5000
    command: python manage.py run -h 0.0.0.0
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=0
      - APP_SETTINGS=project.server.config.DevelopmentConfig
    depends_on:
      - redis
      - mariadb
    networks:
      - ps-net
    restart: unless-stopped

  worker:
    build:
      context: .
    container_name: worker
    command: python manage.py run_worker
    volumes:
      - .:/usr/src/app
    environment:
      - APP_SETTINGS=project.server.config.DevelopmentConfig
    restart: unless-stopped
    depends_on:
      - redis
      - mariadb
    networks:
      - ps-net

  #  dashboard:
  #    build: ./project/dashboard
  #    container_name: dashboard
  #    ports:
  #      - 9181:9181
  #    command: rq-dashboard -H redis
  #    depends_on:
  #      - redis

  grafana:
    image: grafana/grafana:8.1.5
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - ps-net