x-app: &default-app
  build:
    context: .
  depends_on:
    - db
    - redis
  restart: ${DOCKER_RESTART_POLICY:-unless-stopped}
  stop_grace_period: 3s
  tty: true
  networks:
    - ps-net
  volumes:
    - ${DOCKER_WEB_VOLUME:-.:/usr/src/app}

networks:
  ps-net:
    driver: bridge

volumes:
  grafana_data: { }
  db_data: { }

services:
  web:
    <<: *default-app
    container_name: web
    ports:
      - 5004:5000
    expose:
      - 5000
    command: python manage.py run -h 0.0.0.0
    environment:
      - FLASK_DEBUG=0
      - APP_SETTINGS=project.server.config.DevelopmentConfig

  worker:
    <<: *default-app
    container_name: worker
    command: python manage.py run_worker
    environment:
      - APP_SETTINGS=project.server.config.DevelopmentConfig

  redis:
    container_name: redis
    image: redis:6.2.6-buster
    restart: ${DOCKER_RESTART_POLICY:-unless-stopped}
    stop_grace_period: 3s
    networks:
      - ps-net

  db:
    image: mysql:8.0.27
    container_name: db
    restart: ${DOCKER_RESTART_POLICY:-unless-stopped}
    stop_grace_period: 3s
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    #      - ./:/docker-entrypoint-initdb.d
    networks:
      - ps-net

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    restart: ${DOCKER_RESTART_POLICY:-unless-stopped}
    ports:
      - 7777:8080
    expose:
      - 8080
    volumes:
      - ./adminer.css:/var/www/html/adminer.css
    networks:
      - ps-net

  #  dashboard:
  #    build: ./project/dashboard
  #    container_name: dashboard
  #    ports:
  #      - 9181:9181
  #    command: rq-dashboard -H redis
  #    depends_on:
  #      - redis

  grafana:
    image: grafana/grafana:8.1.5
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: ${DOCKER_RESTART_POLICY:-unless-stopped}
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - ps-net