{
 "title": "Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Days Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMPDIFF(DAY , NOW(), timestamp)*-1 as metric FROM portfolio ORDER BY timestamp ASC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Portfolio Entries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) as metric FROM portfolio;"
    }
   ]
  },
  {
   "title": "Sentry Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "projectIds": [ "5984692" ], "statsCategory": [ "error" ], "statsFields": [ "sum(quantity)" ] }
   ]
  },
  {
   "title": "Sentry Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "projectIds": [ "5984692" ], "statsCategory": [ "transaction" ], "statsFields": [ "sum(quantity)" ] }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  success AS \"S\"\nFROM job\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) as count FROM job WHERE success = 1;"
    }
   ]
  },
  {
   "title": "Portfolio Performance",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TIME_TO_SEC(duration) as metric FROM job WHERE job = \"portfolio\";"
    }
   ]
  },
  {
   "title": "Marketcap Performance",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TIME_TO_SEC(duration) as metric FROM job WHERE job = \"marketcap\";"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMPDIFF(MINUTE, NOW(), timestamp)*-1 as MinutesAgo, job as Job, success as Success, TIME_TO_SEC(duration) as Duration, error as Error FROM job ORDER BY id DESC LIMIT 18;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) as count FROM job WHERE success = 0;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) as count FROM job WHERE success = 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT job as Job, COUNT(*) AS \"Count\" FROM job GROUP BY job;"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, TIME_TO_SEC(duration) as Portfolio FROM job WHERE job = \"portfolio\" ORDER BY id ASC;"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, TIME_TO_SEC(duration) as Portfolio FROM job WHERE job = \"marketcap\" ORDER BY id ASC;"
    }
   ]
  },
  {
   "title": "AVG",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT TIME_TO_SEC(duration) as metric FROM job WHERE job = \"portfolio\";"
    }
   ]
  },
  {
   "title": "MIN",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 5, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "SELECT TIME_TO_SEC(duration) as metric FROM job WHERE job = \"portfolio\";"
    }
   ]
  },
  {
   "title": "MAX",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT TIME_TO_SEC(duration) as metric FROM job WHERE job = \"portfolio\";"
    }
   ]
  },
  {
   "title": "FAIL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 7, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) as metric FROM job WHERE job = \"portfolio\" AND success = 0;"
    }
   ]
  },
  {
   "title": "AVG",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT TIME_TO_SEC(duration) as metric FROM job WHERE job = \"marketcap\";"
    }
   ]
  },
  {
   "title": "MIN",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "SELECT TIME_TO_SEC(duration) as metric FROM job WHERE job = \"marketcap\";"
    }
   ]
  },
  {
   "title": "MAX",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 10, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT TIME_TO_SEC(duration) as metric FROM job WHERE job = \"marketcap\";"
    }
   ]
  },
  {
   "title": "FAIL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 11, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) as metric FROM job WHERE job = \"marketcap\" AND success = 0;"
    }
   ]
  },
  {
   "title": "Worker",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT lifetime as Lifetime, working_time as WorkingTime, failed as Failed, successful as Successful FROM worker;"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, TIME_TO_SEC(duration) as Portfolio FROM job WHERE job = \"portfolio\" ORDER BY id ASC;"
    },
    {
     "rawSql": "SELECT timestamp as time, TIME_TO_SEC(duration) as Marketcap FROM job WHERE job = \"marketcap\" ORDER BY id ASC;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT TIMESTAMPDIFF(MINUTE, NOW(), timestamp)*-1 as MinutesAgo, job as Job, success as Success, TIME_TO_SEC(duration) as Duration, error as Error FROM job WHERE job = \"daily\" OR job = \"pnl\" ORDER BY id DESC LIMIT 5;"
    }
   ]
  }
 ]
}