{
 "title": "Portfolio",
 "time": { "from": "2021-12-18T23:00:00.000Z", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Market", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  total AS \"btc_usd\"\nFROM portfolio\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "BTC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  btc_usd AS \"btc_usd\"\nFROM portfolio\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "ETH",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  eth_usd AS \"btc_usd\"\nFROM portfolio\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Y. PNL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  pnl AS \"btc_usd\"\nFROM pnl\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Y. PNL %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  current_24h AS \"btc_usd\"\nFROM pnl\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "MC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  total_market_cap AS \"btc_usd\"\nFROM global\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "ALT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  altcoin_market_cap AS \"btc_usd\"\nFROM global\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "SC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  stablecoin_market_cap AS \"btc_usd\"\nFROM global\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "FUT V",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  derivatives_volume_24h AS \"btc_usd\"\nFROM global\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Fear & Greed",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value as metric FROM fng ORDER BY timestamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "CBBI",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT confidence as metric FROM cbbi ORDER BY timestamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "MC V",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  total_volume_24h AS \"btc_usd\"\nFROM global\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "ALT V",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  altcoin_volume_24h AS \"btc_usd\"\nFROM global\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "SC V",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  stablecoin_volume_24h AS \"btc_usd\"\nFROM global\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  btc_dominance AS \"BTC\",\n  eth_dominance AS \"ETH\",\n  (100 - btc_dominance - eth_dominance) AS \"ALT\"\nFROM global"
    }
   ]
  },
  { "title": "Portfolio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,15m),\n  avg(current) AS \"Total\"\nFROM portfolio\nWHERE\n  $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY $__timeGroup(timestamp,15m)"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  current\nFROM portfolio\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "BTC - T",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  current_btc\nFROM portfolio\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "24H - T",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  current_24h\nFROM portfolio\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "1W - T",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  current_1w\nFROM portfolio\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Bitmex",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  bitmex_total\nFROM portfolio\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "BTC - BI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  bitmex_total_btc\nFROM portfolio\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "24H - BI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  bitmex_total_24h\nFROM portfolio\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "1W - BI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  bitmex_total_1w\nFROM portfolio\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Binance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  binance_total\nFROM portfolio\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "BTC - BN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  binance_total_btc\nFROM portfolio\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "24H - BN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  binance_total_24h\nFROM portfolio\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "1W - BN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  binance_total_1w\nFROM portfolio\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Atari",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  atari_total\nFROM portfolio\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "BTC - A",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  atari_total_btc\nFROM portfolio\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "24H - A",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  atari_1d\nFROM portfolio\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "1W - A",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  atari_7d\nFROM portfolio\nORDER BY timestamp DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "24 - Total vs. Bitmex vs. Binance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,4h),\n  avg(bitmex_total_24h) AS \"Bitmex\",\n  avg(binance_total_24h) AS \"Binance\",\n  avg(current_24h) AS \"Total\"\nFROM portfolio\nWHERE\n  $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY $__timeGroup(timestamp,4h)"
    }
   ]
  },
  {
   "title": "PNL - Total vs. Bitmex vs. Binance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,1d),\n  avg(bitmex_total_24h) AS \"Bitmex\",\n  avg(binance_total_24h) AS \"Binance\",\n  avg(current_24h) AS \"Total\"\nFROM pnl\nWHERE\n  $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY $__timeGroup(timestamp,1d)"
    }
   ]
  },
  {
   "title": "Total vs. BTC",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,1h),\n  avg(total) AS \"Total\",\n  avg(btc_usd) AS \"BTC\"\nFROM portfolio\nWHERE\n  $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY $__timeGroup(timestamp,1h)"
    }
   ]
  },
  {
   "title": "Binance Alocation",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  currency AS metric,\n  balance\nFROM binance_balances\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Alocation",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 19, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  binance_total AS \"Binance\",\n  bitmex_total AS \"Bitmex\",\n  atari_total AS \"Atari\"\nFROM portfolio\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Binance vs. Bitmex",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,1h),\n  avg(binance_total) AS \"Binance\",\n  avg(bitmex_total) AS \"Bitmex\"\nFROM portfolio\nWHERE\n  $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY $__timeGroup(timestamp,1h)"
    }
   ]
  },
  {
   "title": "Binance / Bitmex",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,1h),\n  avg(binance_total/bitmex_total) AS \"Binance / Bitmex\"\nFROM portfolio\nWHERE\n  $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY $__timeGroup(timestamp,1h)"
    }
   ]
  },
  { "title": "Binance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Orders to Market",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT symbol AS metric, market_percentage FROM binance_orders ORDER BY market_percentage"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT symbol as Symbol, side as Side, amount as Amount, price as Price, market as Market, market_percentage as MP FROM binance_orders ORDER BY market_percentage;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT currency as Currency, balance as Balance, amount as Amount, b.price as Price, m.`1d_price_change_pct` as \"24H\", m.`7d_price_change_pct` as \"1W\", used_percentage as Used FROM binance_balances b JOIN marketcap m on b.currency = m.symbol ORDER BY balance DESC;"
    }
   ]
  },
  { "title": "Marketcap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Marketcap",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT id as \"Rank\", rank_delta as Delta, symbol as Symbol, name as Name, price as Price, marketcap as Marketcap, marketcap_dominance as Dominace, 1d_price_change_pct as 1D, 7d_price_change_pct as 1W, 30d_price_change_pct as 1M, 7d_volume_change_pct as \"1W vol\", 30d_volume_change_pct as \"1M vol\" FROM marketcap ORDER BY id;"
    }
   ]
  }
 ]
}